\documentclass[12pt]{article} % article?
\usepackage{geometry} %
\geometry{a4paper} % or letter or a5paper or ... etc
\usepackage{graphicx}
\usepackage{amssymb,amsmath, bm}
\geometry{letterpaper, top=1in, left=1in, right=1in, bottom=1in} % to set margins

\usepackage{setspace}
\onehalfspacing

\title{A model for cross-protection}
\author{Nicholas G Reich}


%%% BEGIN DOCUMENT
\begin{document}

%opts_chunk$set(concordance=TRUE, tidy=TRUE)

\maketitle


\section{Modeling interactions between multiple disease strains}
\subsection{A disease transmission model}
We specify a model for a multivariate time series, measured in discrete time units. Each time series, representing case counts for a particular disease is represented by $Y_{i,t}$, the number of incident observed cases of disease $i$ within a particular time window $t$. Furthermore, $X_{i,t}$ are the total number of incident cases (both reported and unreported) in time $t$. The theoretical transmission model (adapted from Finkenstadt and Grenfell) could be written as
\begin{equation}
X_{i,t} = \beta_t \cdot X_{i,t-1}^{\alpha_1} \cdot S_{i,t-1}^{\alpha_2}
\end{equation}
where $S_{i,t}$ is the number of susceptible individuals to disease $i$ at time $t$ and 
% lifted from supplemental materials of JRSI paper
the $\beta_t$ are a time-varying transmission parameters.  
The $\alpha$ are mixing parameters, which, if both equal 1, define a population with homogeneous mixing whereas values not equal to 1 have been used to describe departures from mass-action mixing 
%\cite{liu1987dynamical} 
and to account for discretization of continuous time transmission processes 
%\cite{glass2003interpreting}
.


Therefore, a statistical formulation of the theoretical transmission model would be
\begin{eqnarray}
\log {\mathbb E}[ X_{i,t}|X_{\cdot,t-1}, S_{i,t-1}] & = & \log\beta_t + \alpha_1 \log X_{i,t-1} + \alpha_2 \log S_{i,t-1}
\end{eqnarray}
where the $\beta_t$ coefficients represent the seasonal baselines, i.e. $\beta_t = \beta_{t \mod 26}$ if our timestep is biweeks. We intentionally leave the distributional assumption for $X_{i,t}$ unspecified for now, although it might be specified as Poisson or Negative Binomial.



\subsection{approximating susceptibility}
Finkenstadt and Grenfell used a Taylor series expansion to approximate the susceptible counts at each time step and to estimate the reporting fractions. Here, we propose an alternate approximation to the susceptible counts for each strain. We could say that 
\begin{equation}
S_{i,t} = \bar S_i \cdot \exp (\gamma M^*_{i,t})
\end{equation}
where $M^*_{i,t}$ is a continuous measure that acts (when exponentiated) as a scaling factor on the mean susceptibility to a particular strain, and $\gamma$ is a coefficient. The model equation then becomes:
\begin{eqnarray}
\log {\mathbb E}[ X_{i,t}|X_{\cdot,t-1}, S_{i,t-1}] & = & \log\beta_t + \alpha_1 \log X_{i,t-1} + \alpha_2 \left( \log \bar S_{i} + \gamma M^*_{i,t} \right )\\
 & = & \log\beta_t + \alpha_1 \log X_{i,t-1} + \alpha_2 \log \bar S_{i} + \gamma^* M^*_{i,t}
\end{eqnarray}
If we can find, then, a decent measure for $M^*$, the above model should not be terribly difficult to fit.

For a simple first pass at $M$, we might assume that it takes the form of a ``memory term'' that for a particular strain $i$ has two components (1) a sum of recent previous cases from strain $i$, representing recent additions to the susceptible class,  and (2) a weighted sum of prior cases of other strains, representing the current balance of those cross-protected from other strains. Assume that cases become cross-protected upon infection with other strains and leave the cross-protected pool at an exponential rate, $\theta$.  One definition of $M$ could be as follows. For a fixed $k$ (a duration into the past that we sum the prior cases) and $\theta$:
\begin{eqnarray*}
M_{i,t}&=& \sum_{t-k < t'< t} X_{i,t'} + \sum_{j \neq i} \sum_{t-k < t'< t} X_{j,t'}\cdot \mbox{Pr(case infected at $t'$ still protected at time $t$)} \\ 
&=&\sum_{t-k < t'< t} X_{i,t'} +  \sum_{j \neq i}  \sum_{t-k < t'< t} X_{j,t'}\cdot e^{-\theta (t-t')}.
\end{eqnarray*}
Then, we can standardize the $M$ terms as 
$$M^*_{i,t} = \frac{M_{i,t} - \bar M_i}{sd(M_{i,t})}.$$
Then, if we use this $M^*$ term in the above model, and assume that a Poisson model is fit, we could interpret $e^{\gamma^*}$ as the relative rate between two timepoints that have the same $X_{i,t-1}$ value but where one point has 1 standard deviation greater measure of susceptibility. (this interpretation assumes that $\alpha_2 =1$.


\subsection{Analyzing Simulated Data}
I analyzed 12000 simulated datasets from a four-strain model with 2000 datasets at each of 6 different levels of cross-protection. The model fit to the data was 
\begin{eqnarray}
X_{i,t} &\sim & Poisson(\lambda_{i,t})\\
\log \lambda_{i,t} &=& \beta_{1,i} + \beta_2 \log (X_{i,t-1}+1) + \beta_3 M^*_{i,t}
\end{eqnarray}

I fit the model above for a fixed $k=300$ and for $\theta = 1, 2, ..., 104$ (i.e. for cross-protection values of up to 4 years). For each sequence of 104 models, across the different values of $\theta$, the model with the highest log-likelhood value was chosen and the results reported here.

We can see from Figure \ref{fig:boxplot} shows that the estimated $\hat\theta$ values increase as the true value of $\theta$ increases. The median values of $\hat\theta$ appear to be higher than the true values of $\theta$, a difference that is more pronounced for smaller true values of $\theta$.

<<boxplotThetas, echo=FALSE, fig.cap="estimated $\\hat\\theta$ (y-axis, in biweeks) and the known true value of $\\theta$ (x-axis) faceted by the reported fraction of cases">>=
setwd('~/Documents/code_versioned/pompSandbox/memory/')
results <- read.csv("simResults_20140522.csv")
results <- as.data.frame(results)
results$trueLambda <- 26/results$delta
results$thetaFac <- factor(results$trueLambda, labels=c("1 d", "6 mo", "1 yr", "1.5 yrs", "2 yrs", "3 yrs"))
qplot(thetaFac, lambda, data=results, geom="boxplot", facets=.~rho) + 
        ylab(expression(hat(theta))) + xlab(expression(theta))
@

<<boxplotBetaMs, echo=FALSE, fig.cap="estimated $\\hat\\beta_3$ (y-axis) and the known true value of $\\theta$ (x-axis) faceted by the reported fraction of cases">>=
qplot(thetaFac, beta_M, data=results, geom="boxplot", facets=.~rho) + 
        ylab(expression(hat(beta)[3])) + xlab(expression(theta))
@

The confidence interval coverage is terrible (i.e. less than 50\%) and the ``estimates'' of $\theta$ are also quite poor, often showing 50\% bias or greater. So this algorithm clearly has shortcomings if one is trying to draw specific inference about the duration of cross-protection, but it does appear that we could use it to evaluate whether cross-protection exists within a given system.
<<cpPresentTable, echo=FALSE>>=
results$cpPresent <- results$lambda_ci_low>0
presentTable <- round(with(results, table(thetaFac, cpPresent))/20,1)
@

If we classify each dataset as either having or not having cross-protection based on whether the 95\% confidence interval for $\theta$ (based on $\chi^2$ likelihood ratio confidence intervals) includes zero, this turns out to serve as a fairly good classification rule. In particular, Table \ref{tab:present} shows that our sensitivity (the probability of correctly classifying a dataset that was generated with cross-protection as having cross-protection) ranges from between \Sexpr{min(presentTable[2:6,2])} to \Sexpr{max(presentTable[2:6,2])}, and in increases as the true duration of cross-protection lengthens. Similarly, our specificity (the probability of correctly classifying a dataset that was generated with no cross-protection) is \Sexpr{presentTable[1,1]}. The sensitivity and specificity of our previously published model on these same datasets were 100\% and 77\%, respectively.

<<printTable, echo=FALSE, results='asis', message=FALSE, >>=
require(xtable)
xtable(presentTable, caption="Percent of datasets classified as having cross-protection (TRUE) or not (FALSE), by the true duration of cross-protection.", digits=1, label="tab:present")
@

\section{Analyzing real data}

\subsection{Cross-protection between serotypes of dengue}

<<echo=FALSE, message=FALSE>>=
source('fourStrainMemory.R')
@


<<dengue, echo=FALSE, fig.cap="Likelihood profile for $\\theta$ in the four-serotype dengue model.", message=FALSE>>=
## run Dengue analysis
load("/Users/nick/Dropbox/work/research/dengueCrossProtection/data/bkk.dengue.cases.new.rda")
dengue_data <- bkk.dengue.cases[,3:6]
dengue_data[which(dengue_data<0, arr.ind=TRUE)] <- 0 ## remove negative values
tmp <- runCrossProtectMemoryAnalysis(data=dengue_data, k=300, 
                                     max_lambda=26*6, 
                                     plot=TRUE, verbose=FALSE)
@
I fit the model above, to the four-serotype dengue dataset from Queen Sirikit. Using $k$=300 and setting $\theta$ to be at most six years (156 biweeks), we find that the $\hat\theta = $\Sexpr{round(tmp["lambda"])} biweeks, with a 95\% CI of (\Sexpr{round(tmp["lambda_ci_low"])}, \Sexpr{round(tmp["lambda_ci_high"])}). Overall, there is not strong evidence for cross-protection based on this analysis. Although we do not have a measure of this algorithm's performance when reporting rates are changing, as our method may rely on fairly consistent reporting over time. Figure \ref{fig:dengue} shows the likelihood profile across examined values of $\theta$. The curvature seems dramatic, but the absolute magnitude changes are quite small.

\subsection{Cross-protection between common respiratory pathogens}
We have a decade's worth of data on common respiratory pathogens from a pediatric hospital in the US. Using this data, I fit the model above to the time series of cases from subsets of the following pathogens influenza A, influenza B, RSV, adenovirus, rhinovirus, parainfluenza, and enterovirus. Some things to note:
\begin{itemize}
\item We might expect to pick up more spurious associations with these data on different pathogens if external factors drive these pathogens into different/shifted seasonal patterns. Our algorithm might pick up different seasonal patterns as evidence of cross-protection. A simulation study could test this out. Enterovirus might be a good example of this, as there might not be a strong biological explanation for why there would be interference between it and a respiratory pathogen.
\item In general, we might expect the duration of cross-protection/interference to be shorter between these viruses, and this dataset is shorter than the others, so we have set $k=120$ and $\theta=100$.
\item Still to do: generalize code to be able to look at different numbers of interacting pathogens.
\item to investigate: impact of changing reporting rates over time on the ability of this metric to detect cross-protection.
\end{itemize}


<<echo=FALSE, fig.cap="Likelihood profile for $\\theta$ in a model for RSV, flu A, flu B, and parainfluenza.", message=FALSE>>=
rsv_data <- read.csv("/Users/nick/Dropbox/work/research/maskStudy/manuscripts/ALERTv2/dataCleaned/chco.csv")
rsv_data_subset <- rsv_data[,c("RSV", "Total.Flu.A", "Flu.B", "Paraflu")]
tmp <- runCrossProtectMemoryAnalysis(data=rsv_data_subset, k=120, 
                                     max_lambda=100, 
                                     plot=TRUE, verbose=FALSE)
@

\end{document}